from collections import defaultdict
import json
rooms = 0  # the total number of rooms

# Opening JSON file - to read the adjacency types and the user constraints
# f = open('input.json')

# # returns JSON object as 
# # a dictionary
# data = json.load(f)

# f.close()
# f=open('output.json') # for the placements generated by gplan
# out_data=json.load(f)
# f.close()

# print(len(data['nodes']))
# print(data['exterior_rooms']['west'])
# print(data['exterior_rooms']['west'][1])
# print(out_data['floorplans'][0][0])

num_sx, num_tx, num_sy, num_ty = 0, 0, 0, 0
sx_adj = []
sy_adj = []
tx_adj=[]
ty_adj=[]

adjacent_pairs = 0
adj = defaultdict(list)  # contains the adjacency of all the rooms
adj_type = {}

edgesX = []
edgesY = []
edges_setx = []
edges_sety = []

NEG_INF = -1e8
POS_INF = 1e8

lb_len = []
ub_len = []
lb_width = []
ub_width = []
plot_width = 0
plot_height = 0

placementx = []
placementy = []

rotx1=[]
rotx2=[]
roty1=[]
roty2=[]

irreg_nodes_map = {}
door_connectivity_edges = set()
"""
LEFT WALL - 1
TOP WALL - 2
RIGHT WALL - 3
BOTTOM WALL - 4

1-3 adjacency - type 1 (the first room in the pair is to the right)
3-1 adjacency - type 2 (the first room in the pair is to the left)
2-4 adjacency - type 3 (the first room in the pair is to the bottom side)
4-2 adjacency - type 4 (the first room in the pair is to the top side)
"""
# extracting information from the read json files
def input_adjacency():
    global adjacent_pairs
    # print("Please enter the number of pairs of rooms that are adjacent: ")
    adjacent_pairs = len(data['edges'])


    # print("Enter adjacencies in this format: ROOM 1, ROOM 2, adjacency type")

    for i in range(adjacent_pairs):
        ri=data['edges'][i]['source']
        rj=data['edges'][i]['target']

        # ri, rj, adj_type_input = map(int, input().split())
        adj_type_input=0
        if data['nodes'][ri-1]['room_x'] + data['nodes'][ri-1]['room_width'] == data['nodes'][rj-1]['room_x']:
            adj_type_input=2
        elif data['nodes'][rj-1]['room_x'] + data['nodes'][rj-1]['room_width'] == data['nodes'][ri-1]['room_x']:
            adj_type_input=1
        elif data['nodes'][ri-1]['room_y'] - data['nodes'][ri-1]['room_height'] == data['nodes'][rj-1]['room_y']:
            adj_type_input=4
        else :
            adj_type_input=3
        if adj_type_input < 1 or adj_type_input > 4:
            # print("WRONG TYPE OF ADJACENCY")
            exit(1)

        adj_type[(ri, rj)] = adj_type_input
        if adj_type_input % 2:
            adj_type[(rj, ri)] = adj_type_input + 1
        else:
            adj_type[(rj, ri)] = adj_type_input - 1

        adj[ri].append(rj)
        adj[rj].append(ri)


# helper function to extract the the useful information from the json objects read
def  tblr_rooms(): 
    global num_sx, num_sy, sx_adj, sy_adj, edges_setx, edges_sety,num_tx,tx_adj,num_ty,ty_adj

    # print("Please enter the number of rooms that are to be connected to sx:")
    num_sx = len(data['boundary_rooms']['west'])

    # print("Please enter those rooms:")
    for i in range(num_sx):
        a = data['boundary_rooms']['west'][i]
        sx_adj.append(a)
        edges_setx.append((0, 2 * a - 1))
        edgesX[0][2 * a - 1] = 0

    # print("Please enter the number of rooms that are to be connected to sy:")
    num_sy = len(data['boundary_rooms']['south'])

    # print("Please enter those rooms:")
    for i in range(num_sy):
        a = data['boundary_rooms']['south'][i]
        sy_adj.append(a)
        edges_sety.append((0, 2 * a))
        edgesY[0][2 * a] = 0

    num_tx = len(data['boundary_rooms']['east'])

    for i in range(num_tx):
        a = data['boundary_rooms']['east'][i]
        tx_adj.append(a)
        edges_setx.append((2 * a, 2*len(data['nodes'])+1))
        edgesX[2 * a][2*len(data['nodes'])+1] = 0    

    num_ty = len(data['boundary_rooms']['north'])    

    for i in range(num_ty):
        a = data['boundary_rooms']['north'][i]
        ty_adj.append(a)
        edges_sety.append((2 * a - 1, 2*len(data['nodes'])+1))
        edgesY[2 * a - 1][2*len(data['nodes'])+1] = 0


# populates the structures with the user constraints to be further used in the longest path caculations
def input_constraints():
    global lb_len, ub_len, lb_width, ub_width

    # print("For each room, please enter the lower and upper bounds for length and width")

    lb_len.append(-1)
    ub_len.append(-1)
    lb_width.append(-1)
    ub_width.append(-1)

    for i in range(1, rooms + 1):
        # print(f"For room {i}, please enter the lower and upper bounds for length and width")
        
        # print("Lower Length:")
        low_len = float(data['nodes'][i-1]['min_height'])
        # print("Upper Length:")
        up_len = float(5*data['nodes'][i-1]['min_height'])

        # print("Lower Width:")
        low_width = float(data['nodes'][i-1]['min_width'])
        # print("Upper Width:")
        up_width = float(5*data['nodes'][i-1]['min_width'])

        lb_len.append(low_len)
        ub_len.append(up_len)
        lb_width.append(low_width)
        ub_width.append(up_width)


# wrapper function to take the input data
def input_data():
    global rooms, edgesX, edgesY,adj

    # print("Please enter the number of rooms:")
    rooms = len(data['nodes'])

    edgesX = [[POS_INF for _ in range(2 * (rooms + 1))] for _ in range(2 * (rooms + 1))]
    edgesY = [[POS_INF for _ in range(2 * (rooms + 1))] for _ in range(2 * (rooms + 1))]

    tblr_rooms()
    
    adj.clear()
    adj = defaultdict(list)
    input_constraints()
    input_adjacency()


#  adding necessary edges pertaining to the adjacency and constraints to the constraint graphs
def construct_constraintgraphX(small_positive = 0.5):
    global edgesX, edgesY, edges_setx, edges_sety

    # Add limiter of plot width if provided
    if plot_width > 0:
        edgesX[2 * rooms + 1][0] = -1 * plot_width
        edges_setx.append((2 * rooms + 1, 0)) 

    # Add edges for widths of each single room - the user constraints
    for i in range(1, rooms + 1):
        left_wall = 2 * i - 1
        right_wall = 2 * i
        edgesX[left_wall][right_wall] = lb_width[i]
        edgesX[right_wall][left_wall] = -1 * ub_width[i]
        edges_setx.append((left_wall, right_wall))
        edges_setx.append((right_wall, left_wall))

    # Add edges for adjacencies
    for i in range(1, rooms + 1):
        left_wall_i = 2 * i - 1
        right_wall_i = 2 * i
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i

        for x in adj[i]:
            for j in range(len(data['edges'])):
                if (data['edges'][j]['source'] == x and data['edges'][j]['target'] == i) or (data['edges'][j]['source'] == i and data['edges'][j]['target'] == x) :
                    if(data ['edges'][j]['color'] == 'red') :
                        small_positive = 3
                    elif(data ['edges'][j]['color'] == 'black') :
                        small_positive=0.5


            left_wall_x = 2 * x - 1
            right_wall_x = 2 * x
            top_wall_x = 2 * x - 1
            bottom_wall_x = 2 * x

            type_val = adj_type[(i, x)]
            if type_val == 1:
                # i is to the right
                edgesX[right_wall_x][left_wall_i] = 0
                edgesX[left_wall_i][right_wall_x] = 0
                edges_setx.append((right_wall_x, left_wall_i))
                edges_setx.append((left_wall_i, right_wall_x))
                
                # Constraints for top walls
                edgesY[top_wall_i][bottom_wall_x] = NEG_INF
                edgesY[bottom_wall_x][top_wall_i] = small_positive
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))

                edgesY[top_wall_x][bottom_wall_i] = NEG_INF
                edgesY[bottom_wall_i][top_wall_x] = small_positive
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))

            elif type_val == 2:
                # i is to the left
                edgesX[left_wall_x][right_wall_i] = 0
                edgesX[right_wall_i][left_wall_x] = 0
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))
                
                # Constraints for top walls
                edgesY[top_wall_i][bottom_wall_x] = NEG_INF
                edgesY[bottom_wall_x][top_wall_i] = small_positive
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))

                edgesY[top_wall_x][bottom_wall_i] = NEG_INF
                edgesY[bottom_wall_i][top_wall_x] = small_positive
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))


# same as above in Y direction
def construct_constraintgraphY(small_positive = 0.5):
    global edgesX, edgesY, edges_setx, edges_sety

    # Add limiter of plot height if provided
    if plot_height > 0:
        edgesY[2 * rooms + 1][0] = -1 * plot_height
        edges_sety.append((2 * rooms + 1, 0)) 

    # Add edges for the same room
    for i in range(1, rooms + 1):
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i
        edgesY[bottom_wall_i][top_wall_i] = lb_len[i]
        edgesY[top_wall_i][bottom_wall_i] = -1 * ub_len[i]
        edges_sety.append((bottom_wall_i, top_wall_i))
        edges_sety.append((top_wall_i, bottom_wall_i))

    for i in range(1, rooms + 1):
        left_wall_i = 2 * i - 1
        right_wall_i = 2 * i
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i
        
        for x in adj[i]:
            for j in range(len(data['edges'])):
                if (data['edges'][j]['source'] == x and data['edges'][j]['target'] == i) or (data['edges'][j]['source'] == i and data['edges'][j]['target'] == x) :
                    if(data ['edges'][j]['color'] == 'red') :
                        small_positive = 3
                    elif(data ['edges'][j]['color'] == 'black'):
                        small_positive=0.5 
        

            left_wall_x = 2 * x - 1
            right_wall_x = 2 * x
            top_wall_x = 2 * x - 1
            bottom_wall_x = 2 * x

            type_val = adj_type[(i, x)]
            if type_val == 3:
                # i is below x
                edgesY[top_wall_i][bottom_wall_x] = 0
                edgesY[bottom_wall_x][top_wall_i] = 0
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))
                
                # Constraints for the side walls
                edgesX[left_wall_x][right_wall_i] = small_positive
                edgesX[right_wall_i][left_wall_x] = NEG_INF
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))

                edgesX[left_wall_i][right_wall_x] = small_positive
                edgesX[right_wall_x][left_wall_i] = NEG_INF
                edges_setx.append((left_wall_i, right_wall_x))
                edges_setx.append((right_wall_x, left_wall_i))

            elif type_val == 4:
                # x is below i
                edgesY[top_wall_x][bottom_wall_i] = 0
                edgesY[bottom_wall_i][top_wall_x] = 0
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))
                
                # Constraints for the side walls
                edgesX[left_wall_x][right_wall_i] = small_positive
                edgesX[right_wall_i][left_wall_x] = NEG_INF
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))

                edgesX[left_wall_i][right_wall_x] = small_positive
                edgesX[right_wall_x][left_wall_i] = NEG_INF
                edges_setx.append((left_wall_i, right_wall_x))
                edges_setx.append((right_wall_x, left_wall_i))


# helper fucntion to calculate the longest path from s to every other vertex
def pos_longest_path(placement, edge_set, edge_weights):
# this function will need review
    stack = [0]
    edge_visited = [False] * len(edge_set)
    is_pushed = [False] * (2 * rooms + 1)
    is_pushed[0] = True
    # print(edge_set)
    while stack:
        v = stack.pop()
        for i in range(len(edge_set)):
            a, b = edge_set[i]
            if a != v:
                continue
            edge_visited[i] = True
            if edge_weights[a][b] >= 0:
                if placement[b] - placement[a] < edge_weights[a][b]:
                    placement[b] = placement[a] + edge_weights[a][b]
                    stack.append(b)

            for j in range(1, 2 * rooms + 1):
                all_vis = True
                for k in range(len(edge_set)):
                    a, b = edge_set[k]

                    if b == j and edge_weights[a][b] >= 0 and not edge_visited[k]:
                        if edge_weights[a][b] == 0:
                            # print(a)
                            # print(b)
                            x = int((a + 1) / 2)
                            y = int((b + 1) / 2)
                            # print(x)
                            # print(y)
                            if x==0 or adj_type[(x, y)] == 2 or adj_type[(x, y)] == 3:
                                all_vis = False
                        else:
                            all_vis = False

                if all_vis and not is_pushed[j]:
                    stack.append(j)
                    is_pushed[j] = True

    for i in range(len(is_pushed)):
        if not is_pushed[i]:
            return False

    return True


# calculates the longest path from s to every other vertex
def longest_path(placement, edge_set, edge_weights): 
    ctr = 1
    done = False
    total_neg = sum(1 for a, b in edge_set if edge_weights[a][b] < 0)

    # Collects the rooms that are initially adjacent to s
    adj_s = []
    for i in range(len(edge_set)):
        a, b = edge_set[i]
        if a == 0:
            adj_s.append(b)

    while not done and ctr <= total_neg:
        if not pos_longest_path(placement, edge_set, edge_weights):
            return False
        
        ctr += 1
        done = True
        
        # Verifies that at least one room is adjacent to s else no legal placement
        first_room = False
        for x in adj_s:
            if placement[x] == 0:
                first_room = True
        if not first_room:
            done = False
            break

        # Verifies that the plot is not out of bounds
        if (2 * rooms + 1, 0) in edge_set and placement[2 * rooms + 1] > abs(edge_weights[2 * rooms + 1][0]):
            done = False
            break

        for i in range(len(edge_set)):
            a, b = edge_set[i]
            if edge_weights[a][b] < 0:
                if placement[b] - placement[a] < edge_weights[a][b]:
                    placement[b] = placement[a] + edge_weights[a][b]

                    # Checks whether the placements of the walls adjacent to b are also satisfied.
                    stack = [0]
                    stack.append(b)
                    while stack:
                        v = stack.pop()
                        for i in range(len(edge_set)):
                            a, b = edge_set[i]
                            if a != v:
                                continue
                            if edge_weights[a][b] >= 0 and placement[b] - placement[a] < edge_weights[a][b]:
                                '''
                                If b is vertex s, then the lower bound for distance between wall a and s is increased.
                                If all walls initially adjacent to s have their placements changed, then no legal placement exists.
                                '''
                                if b == 0:
                                    edge_weights[a][b] = -1 * placement[a]
                                    continue

                                # Update placements and check if adjacent walls are also satisfied.
                                placement[b] = placement[a] + edge_weights[a][b]
                                stack.append(b)

                    done = False

    if not done:
        print("Returned false in [longest_path]")
    return done



# the final positions of each room printed
def print_placements():
    print("Placements in X dir")
    for i in range(len(placementx)):
        print(i, placementx[i])
    
    print("Placements in Y dir")
    for i in range(len(placementy)):
        print(i, placementy[i])


# the wrapper function to integrate the calls for computing placement
def compute_placement():
    placementx.append(0)  # sx
    placementy.append(0)  # sy
    for i in range(2 * rooms):
        placementx.append(-1)
        placementy.append(-1)

    placementx.append(-1) #tx
    placementy.append(-1) #ty    

    if not longest_path(placementx, edges_setx, edgesX):
        # print("Not able to assign placement in horizontal constraint graph")
        return False
    
    if not longest_path(placementy, edges_sety, edgesY):
        # print("Not able to assign placement in vertical constraint graph")
        return False
    
    return True
        
# debugging functions
def print_edges():
    print("printing horizontal_edges")
    for i in range(len(edges_setx)):
        print(edges_setx[i][0], edges_setx[i][1], edgesX[edges_setx[i][0]][edges_setx[i][1]])

    print("printing vertical_edges")
    for i in range(len(edges_sety)):
        print(edges_sety[i][0], edges_sety[i][1], edgesY[edges_sety[i][0]][edges_sety[i][1]])
 
#for computing range of tolerance of each node
def compute_rot(small_positive = 0.5):
    for i in range(2*rooms):
        rotx1.append(0)#rotx1 represents lower bound of each wall
        rotx2.append(placementx[2*rooms+1])
        roty1.append(0)#represents lower bound of each wall
        roty2.append(placementy[2*rooms+1])

    for i in range(1,rooms+1):
        rotx2[2*i-2]=min(rotx2[2*i-2],placementx[2*i]-data['nodes'][i-1]['min_width'])
        rotx1[2*i-1]=max(rotx1[2*i-1],placementx[2*i-1]+data['nodes'][i-1]['min_width'])
        roty1[2*i-2]=max(roty1[2*i-2],placementy[2*i]+data['nodes'][i-1]['min_height'])
        roty2[2*i-1]=min(roty2[2*i-1],placementy[2*i-1]-data['nodes'][i-1]['min_height'])
    
    #print("debug",roty2[5])
    for i in range(1,rooms+1):
        for x in adj[i]:
            type_val = adj_type[(i, x)]
            if type_val==1:#ith room is on right
                b=data['nodes'][x-1]['min_width']+placementx[2*x-1]
                rotx1[2*i-2]=max(rotx1[2*i-2],b)

            elif type_val==2:#ith room is on left
                a=placementx[2*x]-data['nodes'][x-1]['min_width']
                rotx2[2*i-1]=min(rotx2[2*i-1],a)

            elif type_val==3:#ith room is in bottom
                a=placementy[2*x-1]-data['nodes'][x-1]['min_height']
                roty2[2*i-2]=min(roty2[2*i-2],a)

            elif type_val==4:#ith room is at top
                a=placementy[2*x]+data['nodes'][x-1]['min_height']
                roty1[2*i-1]=max(roty1[2*i-1],a)   
    #print("debug",roty2[5])
    #print("Adjacency list",adj[3])
    for i in range(1,rooms+1):#to handle the small positive 

        for x in adj[i]:
             for j in range(len(data['edges'])):
                if (data['edges'][j]['source'] == x and data['edges'][j]['target'] == i) or (data['edges'][j]['source'] == i and data['edges'][j]['target'] == x) :
                    if(data ['edges'][j]['color'] == 'red') :
                        small_positive = 3
                    elif(data ['edges'][j]['color'] == 'black'):
                        small_positive = 0.5
             #print("Change to be noted",small_positive)
             type_val = adj_type[(i, x)]
             if type_val==1 or type_val==2:
                 a=placementy[2*x]+small_positive
                 b=placementy[2*x-1]-small_positive
                 if roty1[2*i-2]<a:
                    roty1[2*i-2]=a
                 if roty2[2*i-1]>b:
                    #print("small positive",small_positive)
                    #print("change in rot",b,i,x)
                    roty2[2*i-1]=b 
             if type_val==3 or type_val==4:
                 a=placementx[2*x-1]+small_positive
                 b=placementx[2*x]-small_positive
                 if rotx1[2*i-1]<a:
                    rotx1[2*i-1]=a
                 if rotx2[2*i-2]>b:
                    rotx2[2*i-2]=b 
    #print("debug",roty2[5])
    for i in range(1,rooms+1):#to make sure that same walls have same range of tolerance
        for x in adj[i]:
            type_val=adj_type[(i,x)]
            if type_val==1:
                a=max(rotx1[2*i-2],rotx1[2*x-1])
                b=min(rotx2[2*i-2],rotx2[2*x-1])
                rotx1[2*i-2]=a
                rotx1[2*x-1]=a
                rotx2[2*i-2]=b
                rotx2[2*x-1]=b     
            elif type_val==2:
                a=max(rotx1[2*i-1],rotx1[2*x-2])
                b=min(rotx2[2*i-1],rotx2[2*x-2])
                rotx1[2*i-1]=a
                rotx1[2*x-2]=a
                rotx2[2*i-1]=b
                rotx2[2*x-2]=b                           
            elif type_val==3:
                a=max(roty1[2*i-2],roty1[2*x-1])
                b=min(roty2[2*i-2],roty2[2*x-1])
                roty1[2*i-2]=a
                roty1[2*x-1]=a
                roty2[2*i-2]=b
                roty2[2*x-1]=b 
            elif type_val==4:
                a=max(roty1[2*i-1],roty1[2*x-2])
                b=min(roty2[2*i-1],roty2[2*x-2])
                roty1[2*i-1]=a
                roty1[2*x-2]=a
                roty2[2*i-1]=b
                roty2[2*x-2]=b      
    #print("debug",roty2[5])    
                


                

# function for printing range of tolerance
def print_rot():
    print("Range of tolerance in x direction")
    for i in range (2*rooms):
        print(i+1,rotx1[i],rotx2[i])
    print("Range of tolerance in y direction")  
    for i in range (2*rooms):
        print(i+1,roty1[i],roty2[i])

# debugging function
def print_input():
    print(adj_type)
    print(lb_len)
    print(ub_len)
    print(lb_width)
    print(ub_width)

#updating placement of west and south boundary rooms based on range of tolerance to minimize area
def edit_placements():
    for i in range(len(data['boundary_rooms']['west'])):
        j = data['boundary_rooms']['west'][i]
        if rotx2[2*j-2] > placementx[2*j-1]:
            placementx[2*j-1] = rotx2[2*j-2]
            # print('changing x position of wall', j*2-1, 'to ', placementx[2*j-1])
    
    for i in range(len(data['boundary_rooms']['south'])):
        j = data['boundary_rooms']['south'][i]
        if roty2[2*j-1] > placementy[2*j]:
            placementy[2*j] = roty2[2*j-1]
            # print('changing y position of wall ', j*2, 'to ', placementy[2*j])
    
    
# the final file to be given to gplan to show in UI
def return_output():
    global placementx,placementy,data
    out_data={'nodes':[]}
    for i in range(rooms):
        dic={}
        dic.update({'id':data['nodes'][i]['id']})
        if 'label' in data['nodes'][i]:
            dic.update({'label':data['nodes'][i]['label']})
        dic.update({'room_x':float(round(placementx[2*i+1],4))})
        dic.update({'room_y':float(round(placementy[2*i+2],4))})
        dic.update({'width':float(round(placementx[2*i+2],4)-round(placementx[2*i+1],4))})
        dic.update({'height':float(round(placementy[2*i+1],4)-round(placementy[2*i+2],4))})
        out_data['nodes'].append(dic)
    # print(out_data)

    return out_data

 

def reinitialize():
    global rooms,num_sx,num_tx,num_sy,num_ty,sx_adj,sy_adj,adjacent_pairs,adj,adj_type,edgesX,edgesY,edges_setx,edges_sety,lb_len,ub_len,lb_width,ub_width,placementx,placementy,tx_adj,ty_adj,plot_width,plot_height,rotx1,rotx2,roty1,roty2
    rooms = 0
    num_sx, num_tx, num_sy, num_ty = 0, 0, 0, 0
    sx_adj = []
    sy_adj = []
    tx_adj=[]
    ty_adj=[]

    adjacent_pairs = 0
    adj = defaultdict(list)  # contains the adjacency of all the rooms
    adj_type = {}

    edgesX = []
    edgesY = []
    edges_setx = []
    edges_sety = []

    lb_len = []
    ub_len = []
    lb_width = []
    ub_width = []
    plot_width = 0
    plot_height = 0

    placementx = []
    placementy = []

    rotx1=[]
    rotx2=[]
    roty1=[]
    roty2=[]

    irreg_nodes_map.clear()
    door_connectivity_edges.clear()


# main wrapper
def main(input, plot_width, plot_height):
    global data, irreg_nodes_map
    reinitialize()
    data = input

    # Store the all dummy nodes as the value of the irregular rooms they are adjacent to
    if 'mergednodes' in data and 'irreg_nodes1' in data and 'irreg_nodes2' in data:
        for i in range(0, len(data['mergednodes'])):
            irreg_nodes_map[(data['irreg_nodes1'][i], data['irreg_nodes2'][i])] = data['mergednodes'][i]
    
    # If dummy nodes exist, remove the adjacency between irregular rooms as they are now separated by dummy nodes
    if 'dummy_node_adj' in data:
        for a in data['edges']:

            # Add the edges with door connectivity to the door_connectivity_edges set
            if a['color'] == 'black':
                continue

            # If there is door connectivity between irregular nodes separated by a dummy node, add a door connectivity between the dummy node and irregular node instead
            elif (a['source'], a['target']) in irreg_nodes_map:
                door_connectivity_edges.add((irreg_nodes_map[(a['source'], a['target'])], a['target']))
            elif (a['target'], a['source']) in irreg_nodes_map:
                door_connectivity_edges.add((irreg_nodes_map[(a['target'], a['source'])], a['source']))
            else:
                door_connectivity_edges.add((a['source'], a['target']))
        data['edges'].clear()

        # Update modified edge data
        for a in data['dummy_node_adj']:
            color = 'black'
            if ((a[0], a[1]) in door_connectivity_edges or (a[1], a[0]) in door_connectivity_edges):
                color = 'red'
            data['edges'].append({'source':a[0] + 1, 'target':a[1] + 1, 'color':color})
    else:
        for a in data['edges']:
            a['source']=a['source']+1
            a['target']=a['target']+1
    for i in range(len(data['boundary_rooms']['north'])):
        data['boundary_rooms']['north'][i]= data['boundary_rooms']['north'][i]+1
    for i in range(len(data['boundary_rooms']['south'])):
        data['boundary_rooms']['south'][i]= data['boundary_rooms']['south'][i]+1
    for i in range(len(data['boundary_rooms']['east'])):
        data['boundary_rooms']['east'][i]= data['boundary_rooms']['east'][i]+1
    for i in range(len(data['boundary_rooms']['west'])):
        data['boundary_rooms']['west'][i]= data['boundary_rooms']['west'][i]+1
    globals()['plot_width'] = plot_width
    globals()['plot_height'] = plot_height
        
    input_data()  # Take all the necessary inputs
    # print_input()
    construct_constraintgraphX()  # Using the inputs, construct X constraint graph
    construct_constraintgraphY()  # Construct Y constraint graph
    # print_edges()  # Print edges for X and Y constraints
    if not compute_placement():  # Compute placements using longest path algorithm and return false if no legal placement found
        # print_placements()
        return [False, None]
    # print_placements()  # Print computed placements
    compute_rot()
    # print_rot()
    edit_placements()
    out_data = return_output()
    return [True, out_data]

# Main execution
# main(file_path)

if __name__ == "__main__":
    main("input_to_min_dim.json")
