from collections import defaultdict
import json
rooms = 0  # the total number of rooms

# Opening JSON file - to read the adjacency types and the user constraints
# f = open('input.json')

# # returns JSON object as 
# # a dictionary
# data = json.load(f)

# f.close()
# f=open('output.json') # for the placements generated by gplan
# out_data=json.load(f)
# f.close()

# print(len(data['nodes']))
# print(data['exterior_rooms']['west'])
# print(data['exterior_rooms']['west'][1])
# print(out_data['floorplans'][0][0])

num_sx, num_tx, num_sy, num_ty = 0, 0, 0, 0
sx_adj = []
sy_adj = []

adjacent_pairs = 0
adj = defaultdict(list)  # contains the adjacency of all the rooms
adj_type = {}

edgesX = []
edgesY = []
edges_setx = []
edges_sety = []
small_positive = 2
NEG_INF = -1e8
POS_INF = 1e8

lb_len = []
ub_len = []
lb_width = []
ub_width = []

placementx = []
placementy = []
"""
LEFT WALL - 1
TOP WALL - 2
RIGHT WALL - 3
BOTTOM WALL - 4

1-3 adjacency - type 1 (the first room in the pair is to the right)
3-1 adjacency - type 2 (the first room in the pair is to the left)
2-4 adjacency - type 3 (the first room in the pair is to the bottom side)
4-2 adjacency - type 4 (the first room in the pair is to the top side)
"""
# extracting information from the read json files
def input_adjacency():
    global adjacent_pairs
    # print("Please enter the number of pairs of rooms that are adjacent: ")
    adjacent_pairs = len(data['edges'])


    # print("Enter adjacencies in this format: ROOM 1, ROOM 2, adjacency type")

    for i in range(adjacent_pairs):
        ri=data['edges'][i]['source']
        rj=data['edges'][i]['target']

        # ri, rj, adj_type_input = map(int, input().split())
        adj_type_input=0
        if data['nodes'][ri-1]['room_x'] + data['nodes'][ri-1]['room_width'] == data['nodes'][rj-1]['room_x']:
            adj_type_input=2
        elif data['nodes'][rj-1]['room_x'] + data['nodes'][rj-1]['room_width'] == data['nodes'][ri-1]['room_x']:
            adj_type_input=1
        elif data['nodes'][ri-1]['room_y'] - data['nodes'][ri-1]['room_height'] == data['nodes'][rj-1]['room_y']:
            adj_type_input=4
        else :
            adj_type_input=3
        if adj_type_input < 1 or adj_type_input > 4:
            print("WRONG TYPE OF ADJACENCY")
            exit(1)

        adj_type[(ri, rj)] = adj_type_input
        if adj_type_input % 2:
            adj_type[(rj, ri)] = adj_type_input + 1
        else:
            adj_type[(rj, ri)] = adj_type_input - 1

        adj[ri].append(rj)
        adj[rj].append(ri)


# helper function to extract the the useful information from the json objects read
def  tblr_rooms(): 
    global num_sx, num_sy, sx_adj, sy_adj, edges_setx, edges_sety

    # print("Please enter the number of rooms that are to be connected to sx:")
    num_sx = len(data['boundary_rooms']['west'])

    # print("Please enter those rooms:")
    for i in range(num_sx):
        a = data['boundary_rooms']['west'][i]
        sx_adj.append(a)
        edges_setx.append((0, 2 * a - 1))
        edgesX[0][2 * a - 1] = 0

    # print("Please enter the number of rooms that are to be connected to sy:")
    num_sy = len(data['boundary_rooms']['south'])

    # print("Please enter those rooms:")
    for i in range(num_sy):
        a = data['boundary_rooms']['south'][i]
        sy_adj.append(a)
        edges_sety.append((0, 2 * a))
        edgesY[0][2 * a] = 0


# populates the structures with the user constraints to be further used in the longest path caculations
def input_constraints():
    global lb_len, ub_len, lb_width, ub_width

    # print("For each room, please enter the lower and upper bounds for length and width")

    lb_len.append(-1)
    ub_len.append(-1)
    lb_width.append(-1)
    ub_width.append(-1)

    for i in range(1, rooms + 1):
        # print(f"For room {i}, please enter the lower and upper bounds for length and width")
        
        # print("Lower Length:")
        low_len = float(data['nodes'][i-1]['min_height'])
        # print("Upper Length:")
        up_len = 2*float(data['nodes'][i-1]['min_height'])

        # print("Lower Width:")
        low_width = float(data['nodes'][i-1]['min_width'])
        # print("Upper Width:")
        up_width = 2*float(data['nodes'][i-1]['min_width'])

        lb_len.append(low_len)
        ub_len.append(up_len)
        lb_width.append(low_width)
        ub_width.append(up_width)


# wrapper function to take the input data
def input_data():
    global rooms, edgesX, edgesY,adj

    # print("Please enter the number of rooms:")
    rooms = len(data['nodes'])

    edgesX = [[POS_INF for _ in range(2 * (rooms + 1))] for _ in range(2 * (rooms + 1))]
    edgesY = [[POS_INF for _ in range(2 * (rooms + 1))] for _ in range(2 * (rooms + 1))]

    tblr_rooms()
    
    adj.clear()
    adj = defaultdict(list)
    input_constraints()
    input_adjacency()


#  adding necessary edges pertaining to the adjacency and constraints to the constraint graphs
def construct_constraintgraphX():
    global edgesX, edgesY, edges_setx, edges_sety

    # Add edges for widths of each single room - the user constraints
    for i in range(1, rooms + 1):
        left_wall = 2 * i - 1
        right_wall = 2 * i
        edgesX[left_wall][right_wall] = lb_width[i]
        edgesX[right_wall][left_wall] = -1 * ub_width[i]
        edges_setx.append((left_wall, right_wall))
        edges_setx.append((right_wall, left_wall))

    # Add edges for adjacencies
    for i in range(1, rooms + 1):
        left_wall_i = 2 * i - 1
        right_wall_i = 2 * i
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i

        for x in adj[i]:
            left_wall_x = 2 * x - 1
            right_wall_x = 2 * x
            top_wall_x = 2 * x - 1
            bottom_wall_x = 2 * x

            type_val = adj_type[(i, x)]
            if type_val == 1:
                # i is to the right
                edgesX[right_wall_x][left_wall_i] = 0
                edgesX[left_wall_i][right_wall_x] = 0
                edges_setx.append((right_wall_x, left_wall_i))
                edges_setx.append((left_wall_i, right_wall_x))
                
                # Constraints for top walls
                edgesY[top_wall_i][bottom_wall_x] = NEG_INF
                edgesY[bottom_wall_x][top_wall_i] = small_positive
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))

                edgesY[top_wall_x][bottom_wall_i] = NEG_INF
                edgesY[bottom_wall_i][top_wall_x] = small_positive
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))

            elif type_val == 2:
                # i is to the left
                edgesX[left_wall_x][right_wall_i] = 0
                edgesX[right_wall_i][left_wall_x] = 0
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))
                
                # Constraints for top walls
                edgesY[top_wall_i][bottom_wall_x] = NEG_INF
                edgesY[bottom_wall_x][top_wall_i] = small_positive
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))

                edgesY[top_wall_x][bottom_wall_i] = NEG_INF
                edgesY[bottom_wall_i][top_wall_x] = small_positive
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))


# same as above in Y direction
def construct_constraintgraphY():
    global edgesX, edgesY, edges_setx, edges_sety

    # Add edges for the same room
    for i in range(1, rooms + 1):
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i
        edgesY[bottom_wall_i][top_wall_i] = lb_len[i]
        edgesY[top_wall_i][bottom_wall_i] = -1 * ub_len[i]
        edges_sety.append((bottom_wall_i, top_wall_i))
        edges_sety.append((top_wall_i, bottom_wall_i))

    for i in range(1, rooms + 1):
        left_wall_i = 2 * i - 1
        right_wall_i = 2 * i
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i
        
        for x in adj[i]:
            left_wall_x = 2 * x - 1
            right_wall_x = 2 * x
            top_wall_x = 2 * x - 1
            bottom_wall_x = 2 * x

            type_val = adj_type[(i, x)]
            if type_val == 3:
                # i is below x
                edgesY[top_wall_i][bottom_wall_x] = 0
                edgesY[bottom_wall_x][top_wall_i] = 0
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))
                
                # Constraints for the side walls
                edgesX[left_wall_x][right_wall_i] = small_positive
                edgesX[right_wall_i][left_wall_x] = NEG_INF
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))

                edgesX[left_wall_i][right_wall_x] = small_positive
                edgesX[right_wall_x][left_wall_i] = NEG_INF
                edges_setx.append((left_wall_i, right_wall_x))
                edges_setx.append((right_wall_x, left_wall_i))

            elif type_val == 4:
                # x is below i
                edgesY[top_wall_x][bottom_wall_i] = 0
                edgesY[bottom_wall_i][top_wall_x] = 0
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))
                
                # Constraints for the side walls
                edgesX[left_wall_x][right_wall_i] = small_positive
                edgesX[right_wall_i][left_wall_x] = NEG_INF
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))

                edgesX[left_wall_i][right_wall_x] = small_positive
                edgesX[right_wall_x][left_wall_i] = NEG_INF
                edges_setx.append((left_wall_i, right_wall_x))
                edges_setx.append((right_wall_x, left_wall_i))


# helper fucntion to calculate the longest path from s to every other vertex
def pos_longest_path(placement, edge_set, edge_weights):
# this function will need review
    stack = [0]
    edge_visited = [False] * len(edge_set)
    is_pushed = [False] * (2 * rooms + 1)
    is_pushed[0] = True
    print(edge_set)
    while stack:
        v = stack.pop()
        for i in range(len(edge_set)):
            a, b = edge_set[i]
            if a != v:
                continue
            edge_visited[i] = True
            if edge_weights[a][b] >= 0:
                if placement[b] - placement[a] < edge_weights[a][b]:
                    placement[b] = placement[a] + edge_weights[a][b]

            for j in range(1, 2 * rooms + 1):
                all_vis = True
                for k in range(len(edge_set)):
                    a, b = edge_set[k]

                    if b == j and edge_weights[a][b] >= 0 and not edge_visited[k]:
                        if edge_weights[a][b] == 0:
                            print(a)
                            print(b)
                            x = int((a + 1) / 2)
                            y = int((b + 1) / 2)
                            print(x)
                            print(y)
                            if x==0 or adj_type[(x, y)] == 2 or adj_type[(x, y)] == 3:
                                all_vis = False
                        else:
                            all_vis = False

                if all_vis and not is_pushed[j]:
                    stack.append(j)
                    is_pushed[j] = True

    for i in range(len(is_pushed)):
        if not is_pushed[i]:
            return False

    return True


# calculates the longest path from s to every other vertex
def longest_path(placement, edge_set, edge_weights): 
    ctr = 1
    done = False
    total_neg = sum(1 for a, b in edge_set if edge_weights[a][b] < 0)

    while not done and ctr <= total_neg:
        if not pos_longest_path(placement, edge_set, edge_weights):
            return False
        
        ctr += 1
        done = True
        
        for i in range(len(edge_set)):
            a, b = edge_set[i]
            if edge_weights[a][b] < 0:
                if placement[b] - placement[a] < edge_weights[a][b]:
                    placement[b] = placement[a] + edge_weights[a][b]
                    done = False

    if not done:
        print("Returned false in [longest_path]")
    return done



# the final positions of each room printed
def print_placements():
    print("Placements in X dir")
    for i in range(len(placementx)):
        print(i, placementx[i])
    
    print("Placements in Y dir")
    for i in range(len(placementy)):
        print(i, placementy[i])


# the wrapper function to integrate the calls for computing placement
def compute_placement():
    placementx.append(0)  # sx
    placementy.append(0)  # sy
    for i in range(2 * rooms):
        placementx.append(-1)
        placementy.append(-1)

    if not longest_path(placementx, edges_setx, edgesX):
        print("Not able to assign placement in horizontal constraint graph")
    
    if not longest_path(placementy, edges_sety, edgesY):
        print("Not able to assign placement in vertical constraint graph")
        
        
# debuggin functions
def print_edges():
    print("printing horizontal_edges")
    for i in range(len(edges_setx)):
        print(edges_setx[i][0], edges_setx[i][1], edgesX[edges_setx[i][0]][edges_setx[i][1]])

    print("printing vertical_edges")
    for i in range(len(edges_sety)):
        print(edges_sety[i][0], edges_sety[i][1], edgesY[edges_sety[i][0]][edges_sety[i][1]])
 

# debugging function
def print_input():
    print(adj_type)
    print(lb_len)
    print(ub_len)
    print(lb_width)
    print(ub_width)
    
    
# the final file to be given to gplan to show in UI
def create_json():
    global placementx,placementy,data
    out_data={'nodes':[]}
    for i in range(rooms):
        dic={}
        dic.update({'id':data['nodes'][i]['id']})
        dic.update({'room_x':float(round(placementx[2*i+1],4))})
        dic.update({'room_y':float(round(placementy[2*i+2],4))})
        dic.update({'width':float(round(placementx[2*i+2],4)-round(placementx[2*i+1],4))})
        dic.update({'height':float(round(placementy[2*i+1],4)-round(placementy[2*i+2],4))})
        out_data['nodes'].append(dic)
    # print(out_data)

    with open('output_from_min_dim.json', 'w') as json_file:
        json.dump(out_data, json_file,  indent=2)

 

def reinitialize():
    global rooms,num_sx,num_tx,num_sy,num_ty,sx_adj,sy_adj,adjacent_pairs,adj,adj_type,edgesX,edgesY,edges_setx,edges_sety,lb_len,ub_len,lb_width,ub_width,placementx,placementy
    rooms = 0
    num_sx, num_tx, num_sy, num_ty = 0, 0, 0, 0
    sx_adj = []
    sy_adj = []

    adjacent_pairs = 0
    adj = defaultdict(list)  # contains the adjacency of all the rooms
    adj_type = {}

    edgesX = []
    edgesY = []
    edges_setx = []
    edges_sety = []

    lb_len = []
    ub_len = []
    lb_width = []
    ub_width = []

    placementx = []
    placementy = []

# main wrapper
def main(file_path):
    global data
    reinitialize()
    f = open(file_path)
    data = json.load(f)
    for a in data['edges']:
        a['source']=a['source']+1
        a['target']=a['target']+1
    for i in range(len(data['boundary_rooms']['north'])):
        data['boundary_rooms']['north'][i]= data['boundary_rooms']['north'][i]+1
    for i in range(len(data['boundary_rooms']['south'])):
        data['boundary_rooms']['south'][i]= data['boundary_rooms']['south'][i]+1
    for i in range(len(data['boundary_rooms']['east'])):
        data['boundary_rooms']['east'][i]= data['boundary_rooms']['east'][i]+1
    for i in range(len(data['boundary_rooms']['west'])):
        data['boundary_rooms']['west'][i]= data['boundary_rooms']['west'][i]+1
        
    input_data()  # Take all the necessary inputs
    print_input()
    construct_constraintgraphX()  # Using the inputs, construct X constraint graph
    construct_constraintgraphY()  # Construct Y constraint graph
    print_edges()  # Print edges for X and Y constraints
    compute_placement()  # Compute placements using longest path algorithm
    print_placements()  # Print computed placements
    create_json()


# Main execution
# main(file_path)

if __name__ == "__main__":
    main("input_to_min_dim.json")
