from collections import defaultdict
import json
import os
rooms = 0  # the total number of rooms

# Opening JSON file - to read the adjacency types and the user constraints
# f = open('input.json')

# # returns JSON object as 
# # a dictionary
# data = json.load(f)

# f.close()
# f=open('output.json') # for the placements generated by gplan
# out_data=json.load(f)
# f.close()

# print(len(data['nodes']))
# print(data['exterior_rooms']['west'])
# print(data['exterior_rooms']['west'][1])
# print(out_data['floorplans'][0][0])

num_sx, num_tx, num_sy, num_ty = 0, 0, 0, 0
sx_adj = []
sy_adj = []
tx_adj=[]
ty_adj=[]

adjacent_pairs = 0
adj = defaultdict(list)  # contains the adjacency of all the rooms
adj_type = {}

edgesX = []
edgesY = []
edges_setx = []
edges_sety = []

NEG_INF = -1e8
POS_INF = 1e8

# Minimum shared-wall overlap the solver guarantees on every RED adjacency,
# feet. In this solver's input RED marks the DOOR-CONNECTIVITY edges (the
# adjacencies the brief wants doors on - verified live: briefed pairs arrive
# red, the black edges are the extra adjacencies triangulation added) and the
# legacy hardcoded 0.1 is exactly what realised briefed walls as 0.0-0.3 ft
# corner slivers no door can occupy (E2b of
# documentation/plans/VALIDITY_AND_TOPOLOGY_ENGINE_PLAN.md: "each adjacency
# must be at least big enough to fit a door"). 3.0 clears the dresser's 2.8 ft
# door threshold with margin. solve_min_dim retries an infeasible topology at
# the legacy 0.1 before giving up on it, so raising this cannot empty a batch,
# only demote plans to disclosed slivers.
DOOR_OVERLAP_FLOOR = 3.0
adjacency_overlap_floor = DOOR_OVERLAP_FLOOR

lb_len = []
ub_len = []
lb_width = []
ub_width = []
plot_width = 0
plot_height = 0

placementx = []
placementy = []

rotx1=[]
rotx2=[]
roty1=[]
roty2=[]

irreg_nodes_map = {}
door_connectivity_edges = set()
"""
LEFT WALL - 1
TOP WALL - 2
RIGHT WALL - 3
BOTTOM WALL - 4

1-3 adjacency - type 1 (the first room in the pair is to the right)
3-1 adjacency - type 2 (the first room in the pair is to the left)
2-4 adjacency - type 3 (the first room in the pair is to the bottom side)
4-2 adjacency - type 4 (the first room in the pair is to the top side)
"""
# extracting information from the read json files
def input_adjacency():
    global adjacent_pairs
    # print("Please enter the number of pairs of rooms that are adjacent: ")
    adjacent_pairs = len(data['edges'])


    # print("Enter adjacencies in this format: ROOM 1, ROOM 2, adjacency type")

    eps = 0.05
    for i in range(adjacent_pairs):
        ri=data['edges'][i]['source']
        rj=data['edges'][i]['target']

        # Classify the pair's orientation from the CANDIDATE geometry by which
        # walls touch AND whether the perpendicular intervals actually overlap.
        # The old exact `==` chain defaulted every unmatched pair (corner
        # contacts, float jitter) to type 3, wiring garbage constraints that
        # were feasible but meaningless - the solver reported success while the
        # briefed rooms ended up 8 ft apart (found 2026-08-06 chasing E2b).
        ni = data['nodes'][ri-1]
        nj = data['nodes'][rj-1]
        # input room_y is the TOP wall (see the producer note in input_for_min_dim)
        ox = min(ni['room_x'] + ni['room_width'], nj['room_x'] + nj['room_width']) \
            - max(ni['room_x'], nj['room_x'])
        oy = min(ni['room_y'], nj['room_y']) \
            - max(ni['room_y'] - ni['room_height'], nj['room_y'] - nj['room_height'])
        adj_type_input = 0
        if abs(ni['room_x'] + ni['room_width'] - nj['room_x']) < eps and oy > eps:
            adj_type_input = 2   # ri to the left of rj
        elif abs(nj['room_x'] + nj['room_width'] - ni['room_x']) < eps and oy > eps:
            adj_type_input = 1   # ri to the right of rj
        elif abs(ni['room_y'] - ni['room_height'] - nj['room_y']) < eps and ox > eps:
            adj_type_input = 4   # ri above rj
        elif abs(nj['room_y'] - nj['room_height'] - ni['room_y']) < eps and ox > eps:
            adj_type_input = 3   # ri below rj
        else:
            # Corner contact or non-touching in THIS candidate: the arrangement
            # cannot realise the edge as a wall, so there is no orientation to
            # constrain. Skip it - forcing a fake type is worse - and let the
            # API-level adjacency_shortfalls disclosure (E2a) name the pair on
            # the finished plan.
            continue

        adj_type[(ri, rj)] = adj_type_input
        if adj_type_input % 2:
            adj_type[(rj, ri)] = adj_type_input + 1
        else:
            adj_type[(rj, ri)] = adj_type_input - 1

        adj[ri].append(rj)
        adj[rj].append(ri)


# helper function to extract the the useful information from the json objects read
def  tblr_rooms(): 
    global num_sx, num_sy, sx_adj, sy_adj, edges_setx, edges_sety,num_tx,tx_adj,num_ty,ty_adj

    # print("Please enter the number of rooms that are to be connected to sx:")
    num_sx = len(data['boundary_rooms']['west'])

    # print("Please enter those rooms:")
    for i in range(num_sx):
        a = data['boundary_rooms']['west'][i]
        sx_adj.append(a)
        edges_setx.append((0, 2 * a - 1))
        edgesX[0][2 * a - 1] = 0

    # print("Please enter the number of rooms that are to be connected to sy:")
    num_sy = len(data['boundary_rooms']['south'])

    # print("Please enter those rooms:")
    for i in range(num_sy):
        a = data['boundary_rooms']['south'][i]
        sy_adj.append(a)
        edges_sety.append((0, 2 * a))
        edgesY[0][2 * a] = 0

    num_tx = len(data['boundary_rooms']['east'])

    for i in range(num_tx):
        a = data['boundary_rooms']['east'][i]
        tx_adj.append(a)
        edges_setx.append((2 * a, 2*len(data['nodes'])+1))
        edgesX[2 * a][2*len(data['nodes'])+1] = 0    

    num_ty = len(data['boundary_rooms']['north'])    

    for i in range(num_ty):
        a = data['boundary_rooms']['north'][i]
        ty_adj.append(a)
        edges_sety.append((2 * a - 1, 2*len(data['nodes'])+1))
        edgesY[2 * a - 1][2*len(data['nodes'])+1] = 0


# Slack allowed above a room's minimum when the caller gives no maximum.
DEFAULT_UB_FACTOR = 5
# Floor on that slack when the caller DOES give a maximum. In a gapless
# rectangular tiling a column of small rooms must still stack to the same total
# as a column of large ones, so a hard per-room ceiling makes almost every
# topology infeasible and the whole catalogue collapses. The caller's ceiling is
# therefore widened here and enforced exactly later, where the leftover area is
# distributed (api._fill_gaps), which is where the real blow-up happened.
SOLVER_UB_SLACK = float(os.environ.get("GPLAN_SOLVER_UB_SLACK", "2.5"))


def upper_bound(supplied, low, exact=False):
    """Upper bound for one room axis in the longest-path solve.

    Honours a caller-supplied maximum, widened to at least SOLVER_UB_SLACK x the
    minimum so the topology search keeps its freedom, and never looser than the
    historical DEFAULT_UB_FACTOR x the minimum. Falls back to the historical
    bound when no maximum is given, when it is the 99999 "open" sentinel, or
    when it is unusable.
    """
    low = float(low)
    # A fixed room is a hard obstacle in the dissection, not a normal room
    # ceiling.  Normal ceilings deliberately get SOLVER_UB_SLACK so topology
    # search does not collapse; doing that to a stair/lift silently turns an
    # equality into a 2.5x band before any later validator can help.
    if exact:
        return low
    open_ub = DEFAULT_UB_FACTOR * low
    if supplied is None:
        return open_ub
    try:
        value = float(supplied)
    except (TypeError, ValueError):
        return open_ub
    if value <= 0 or value >= 99999:
        return open_ub
    return min(open_ub, max(value, SOLVER_UB_SLACK * low))


# populates the structures with the user constraints to be further used in the longest path caculations
def input_constraints():
    global lb_len, ub_len, lb_width, ub_width

    # print("For each room, please enter the lower and upper bounds for length and width")

    lb_len.append(-1)
    ub_len.append(-1)
    lb_width.append(-1)
    ub_width.append(-1)

    for i in range(1, rooms + 1):
        node = data['nodes'][i-1]

        low_len = float(node['min_height'])
        up_len = upper_bound(node.get('max_height'), low_len,
                             exact=bool(node.get('is_fixed')))

        low_width = float(node['min_width'])
        up_width = upper_bound(node.get('max_width'), low_width,
                               exact=bool(node.get('is_fixed')))

        lb_len.append(low_len)
        ub_len.append(up_len)
        lb_width.append(low_width)
        ub_width.append(up_width)


# wrapper function to take the input data
def input_data():
    global rooms, edgesX, edgesY,adj

    # print("Please enter the number of rooms:")
    rooms = len(data['nodes'])

    edgesX = [[POS_INF for _ in range(2 * (rooms + 1))] for _ in range(2 * (rooms + 1))]
    edgesY = [[POS_INF for _ in range(2 * (rooms + 1))] for _ in range(2 * (rooms + 1))]

    tblr_rooms()
    
    adj.clear()
    adj = defaultdict(list)
    input_constraints()
    input_adjacency()


#  adding necessary edges pertaining to the adjacency and constraints to the constraint graphs
def construct_constraintgraphX(small_positive = 2):
    global edgesX, edgesY, edges_setx, edges_sety

    # Add limiter of plot width if provided
    if plot_width > 0:
        edgesX[2 * rooms + 1][0] = -1 * plot_width
        edges_setx.append((2 * rooms + 1, 0)) 

    # Add edges for widths of each single room - the user constraints
    for i in range(1, rooms + 1):
        left_wall = 2 * i - 1
        right_wall = 2 * i
        edgesX[left_wall][right_wall] = lb_width[i]
        edgesX[right_wall][left_wall] = -1 * ub_width[i]
        edges_setx.append((left_wall, right_wall))
        edges_setx.append((right_wall, left_wall))

    # Precompute edge color lookup: (source, target) -> color (covers both directions)
    edge_color_map = {}
    for e in data['edges']:
        edge_color_map[(e['source'], e['target'])] = e['color']
        edge_color_map[(e['target'], e['source'])] = e['color']

    # Add edges for adjacencies
    for i in range(1, rooms + 1):
        left_wall_i = 2 * i - 1
        right_wall_i = 2 * i
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i

        for x in adj[i]:
            color = edge_color_map.get((x, i)) or edge_color_map.get((i, x))
            if color == 'red':
                small_positive = adjacency_overlap_floor
            elif color == 'black':
                small_positive = 2


            left_wall_x = 2 * x - 1
            right_wall_x = 2 * x
            top_wall_x = 2 * x - 1
            bottom_wall_x = 2 * x

            type_val = adj_type[(i, x)]
            if type_val == 1:
                # i is to the right
                edgesX[right_wall_x][left_wall_i] = 0
                edgesX[left_wall_i][right_wall_x] = 0
                edges_setx.append((right_wall_x, left_wall_i))
                edges_setx.append((left_wall_i, right_wall_x))
                
                # Constraints for top walls
                edgesY[top_wall_i][bottom_wall_x] = NEG_INF
                edgesY[bottom_wall_x][top_wall_i] = small_positive
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))

                edgesY[top_wall_x][bottom_wall_i] = NEG_INF
                edgesY[bottom_wall_i][top_wall_x] = small_positive
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))

            elif type_val == 2:
                # i is to the left
                edgesX[left_wall_x][right_wall_i] = 0
                edgesX[right_wall_i][left_wall_x] = 0
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))
                
                # Constraints for top walls
                edgesY[top_wall_i][bottom_wall_x] = NEG_INF
                edgesY[bottom_wall_x][top_wall_i] = small_positive
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))

                edgesY[top_wall_x][bottom_wall_i] = NEG_INF
                edgesY[bottom_wall_i][top_wall_x] = small_positive
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))


# same as above in Y direction
def construct_constraintgraphY(small_positive = 2):
    global edgesX, edgesY, edges_setx, edges_sety

    # Add limiter of plot height if provided
    if plot_height > 0:
        edgesY[2 * rooms + 1][0] = -1 * plot_height
        edges_sety.append((2 * rooms + 1, 0)) 

    # Add edges for the same room
    for i in range(1, rooms + 1):
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i
        edgesY[bottom_wall_i][top_wall_i] = lb_len[i]
        edgesY[top_wall_i][bottom_wall_i] = -1 * ub_len[i]
        edges_sety.append((bottom_wall_i, top_wall_i))
        edges_sety.append((top_wall_i, bottom_wall_i))

    # Precompute edge color lookup for Y constraint graph (built once, not per room)
    edge_color_map_y = {}
    for e in data['edges']:
        edge_color_map_y[(e['source'], e['target'])] = e['color']
        edge_color_map_y[(e['target'], e['source'])] = e['color']

    for i in range(1, rooms + 1):
        left_wall_i = 2 * i - 1
        right_wall_i = 2 * i
        top_wall_i = 2 * i - 1
        bottom_wall_i = 2 * i

        for x in adj[i]:
            color = edge_color_map_y.get((x, i)) or edge_color_map_y.get((i, x))
            if color == 'red':
                small_positive = adjacency_overlap_floor
            elif color == 'black':
                small_positive = 2


            left_wall_x = 2 * x - 1
            right_wall_x = 2 * x
            top_wall_x = 2 * x - 1
            bottom_wall_x = 2 * x

            type_val = adj_type[(i, x)]
            if type_val == 3:
                # i is below x
                edgesY[top_wall_i][bottom_wall_x] = 0
                edgesY[bottom_wall_x][top_wall_i] = 0
                edges_sety.append((top_wall_i, bottom_wall_x))
                edges_sety.append((bottom_wall_x, top_wall_i))
                
                # Constraints for the side walls
                edgesX[left_wall_x][right_wall_i] = small_positive
                edgesX[right_wall_i][left_wall_x] = NEG_INF
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))

                edgesX[left_wall_i][right_wall_x] = small_positive
                edgesX[right_wall_x][left_wall_i] = NEG_INF
                edges_setx.append((left_wall_i, right_wall_x))
                edges_setx.append((right_wall_x, left_wall_i))

            elif type_val == 4:
                # x is below i
                edgesY[top_wall_x][bottom_wall_i] = 0
                edgesY[bottom_wall_i][top_wall_x] = 0
                edges_sety.append((top_wall_x, bottom_wall_i))
                edges_sety.append((bottom_wall_i, top_wall_x))
                
                # Constraints for the side walls
                edgesX[left_wall_x][right_wall_i] = small_positive
                edgesX[right_wall_i][left_wall_x] = NEG_INF
                edges_setx.append((left_wall_x, right_wall_i))
                edges_setx.append((right_wall_i, left_wall_x))

                edgesX[left_wall_i][right_wall_x] = small_positive
                edgesX[right_wall_x][left_wall_i] = NEG_INF
                edges_setx.append((left_wall_i, right_wall_x))
                edges_setx.append((right_wall_x, left_wall_i))


# helper fucntion to calculate the longest path from s to every other vertex
def pos_longest_path(placement, edge_set, edge_weights):
    """Push placements forward along non-negative edges, releasing a wall only
    once every edge that constrains it has been visited.

    Semantics are unchanged from the original triple-nested version; only the
    bookkeeping is. The original recomputed, for EVERY out-edge of the popped
    vertex, a full scan of all walls x all edges to find which walls were now
    fully visited. That is O(V*E) repeated deg(v) times per pop, and it was 99%
    of total generation time (measured: 202 ms per call, 45.8 s of a 46.2 s
    2BHK run). Two observations remove it:

      * whether an unvisited edge BLOCKS its head is a property of the edge
        alone (its weight and adj_type), constant for the whole call, so it can
        be decided once up front;
      * a wall becomes releasable exactly when its last blocking in-edge is
        visited, so a per-wall counter replaces the rescan.

    Walls are then pushed at the same moment they were before, and `is_pushed`
    still guarantees each is queued once.
    """
    n_walls = 2 * rooms + 1
    out_edges = [[] for _ in range(n_walls + 1)]
    blocking_in = [0] * (n_walls + 1)
    edge_blocks = [False] * len(edge_set)

    for i in range(len(edge_set)):
        a, b = edge_set[i]
        if a < len(out_edges):
            out_edges[a].append(i)
        # Mirror the original predicate exactly. The head range check comes
        # FIRST because the original only ever evaluated this for heads inside
        # range(1, 2*rooms+1): the sink wall 2*rooms+1 maps to an adj_type key
        # that does not exist, so testing it here would raise.
        if 1 <= b <= n_walls - 1 and edge_weights[a][b] >= 0:
            if edge_weights[a][b] == 0:
                x = int((a + 1) / 2)
                y = int((b + 1) / 2)
                blocks = (x == 0 or adj_type.get((x, y)) == 2 or adj_type.get((x, y)) == 3)
            else:
                blocks = True
            if blocks:
                edge_blocks[i] = True
                blocking_in[b] += 1

    stack = [0]
    is_pushed = [False] * n_walls
    is_pushed[0] = True

    # A wall with no blocking in-edge at all was released immediately by the
    # original on its first pass through the j-loop.
    for j in range(1, n_walls):
        if blocking_in[j] == 0 and not is_pushed[j]:
            stack.append(j)
            is_pushed[j] = True

    while stack:
        v = stack.pop()
        for i in out_edges[v]:
            a, b = edge_set[i]
            if edge_weights[a][b] >= 0:
                if placement[b] - placement[a] < edge_weights[a][b]:
                    placement[b] = placement[a] + edge_weights[a][b]
                    stack.append(b)
            if edge_blocks[i]:
                edge_blocks[i] = False
                blocking_in[b] -= 1
                if blocking_in[b] == 0 and not is_pushed[b]:
                    stack.append(b)
                    is_pushed[b] = True

    for i in range(len(is_pushed)):
        if not is_pushed[i]:
            return False

    return True


# calculates the longest path from s to every other vertex
def longest_path(placement, edge_set, edge_weights): 
    ctr = 1
    done = False
    total_neg = sum(1 for a, b in edge_set if edge_weights[a][b] < 0)

    # Collects the rooms that are initially adjacent to s
    adj_s = []
    for i in range(len(edge_set)):
        a, b = edge_set[i]
        if a == 0:
            adj_s.append(b)

    while not done and ctr <= total_neg:
        if not pos_longest_path(placement, edge_set, edge_weights):
            return False
        
        ctr += 1
        done = True
        
        # Verifies that at least one room is adjacent to s else no legal placement
        first_room = False
        for x in adj_s:
            if placement[x] == 0:
                first_room = True
        if not first_room:
            done = False
            break

        # Verifies that the plot is not out of bounds
        if (2 * rooms + 1, 0) in edge_set and placement[2 * rooms + 1] > abs(edge_weights[2 * rooms + 1][0]):
            done = False
            break

        for i in range(len(edge_set)):
            a, b = edge_set[i]
            if edge_weights[a][b] < 0:
                if placement[b] - placement[a] < edge_weights[a][b]:
                    placement[b] = placement[a] + edge_weights[a][b]

                    # Checks whether the placements of the walls adjacent to b are also satisfied.
                    stack = [0]
                    stack.append(b)
                    while stack:
                        v = stack.pop()
                        for i in range(len(edge_set)):
                            a, b = edge_set[i]
                            if a != v:
                                continue
                            if edge_weights[a][b] >= 0 and placement[b] - placement[a] < edge_weights[a][b]:
                                '''
                                If b is vertex s, then the lower bound for distance between wall a and s is increased.
                                If all walls initially adjacent to s have their placements changed, then no legal placement exists.
                                '''
                                if b == 0:
                                    edge_weights[a][b] = -1 * placement[a]
                                    continue

                                # Update placements and check if adjacent walls are also satisfied.
                                placement[b] = placement[a] + edge_weights[a][b]
                                stack.append(b)

                    done = False

    if not done:
        print("Returned false in [longest_path]")
    return done



# the final positions of each room printed
def print_placements():
    print("Placements in X dir")
    for i in range(len(placementx)):
        print(i, placementx[i])
    
    print("Placements in Y dir")
    for i in range(len(placementy)):
        print(i, placementy[i])


# the wrapper function to integrate the calls for computing placement
def compute_placement():
    placementx.append(0)  # sx
    placementy.append(0)  # sy
    for i in range(2 * rooms):
        placementx.append(-1)
        placementy.append(-1)

    placementx.append(-1) #tx
    placementy.append(-1) #ty    

    if not longest_path(placementx, edges_setx, edgesX):
        # print("Not able to assign placement in horizontal constraint graph")
        return False
    
    if not longest_path(placementy, edges_sety, edgesY):
        # print("Not able to assign placement in vertical constraint graph")
        return False
    
    return True
        
# debugging functions
def print_edges():
    print("printing horizontal_edges")
    for i in range(len(edges_setx)):
        print(edges_setx[i][0], edges_setx[i][1], edgesX[edges_setx[i][0]][edges_setx[i][1]])

    print("printing vertical_edges")
    for i in range(len(edges_sety)):
        print(edges_sety[i][0], edges_sety[i][1], edgesY[edges_sety[i][0]][edges_sety[i][1]])
 
#for computing range of tolerance of each node
def compute_rot(small_positive = 2):
    for i in range(2*rooms):
        rotx1.append(0)#rotx1 represents lower bound of each wall
        rotx2.append(placementx[2*rooms+1])
        roty1.append(0)#represents lower bound of each wall
        roty2.append(placementy[2*rooms+1])

    for i in range(1,rooms+1):
        rotx2[2*i-2]=min(rotx2[2*i-2],placementx[2*i]-data['nodes'][i-1]['min_width'])
        rotx1[2*i-1]=max(rotx1[2*i-1],placementx[2*i-1]+data['nodes'][i-1]['min_width'])
        roty1[2*i-2]=max(roty1[2*i-2],placementy[2*i]+data['nodes'][i-1]['min_height'])
        roty2[2*i-1]=min(roty2[2*i-1],placementy[2*i-1]-data['nodes'][i-1]['min_height'])
    
    #print("debug",roty2[5])
    for i in range(1,rooms+1):
        for x in adj[i]:
            type_val = adj_type[(i, x)]
            if type_val==1:#ith room is on right
                b=data['nodes'][x-1]['min_width']+placementx[2*x-1]
                rotx1[2*i-2]=max(rotx1[2*i-2],b)

            elif type_val==2:#ith room is on left
                a=placementx[2*x]-data['nodes'][x-1]['min_width']
                rotx2[2*i-1]=min(rotx2[2*i-1],a)

            elif type_val==3:#ith room is in bottom
                a=placementy[2*x-1]-data['nodes'][x-1]['min_height']
                roty2[2*i-2]=min(roty2[2*i-2],a)

            elif type_val==4:#ith room is at top
                a=placementy[2*x]+data['nodes'][x-1]['min_height']
                roty1[2*i-1]=max(roty1[2*i-1],a)   
    #print("debug",roty2[5])
    #print("Adjacency list",adj[3])
    for i in range(1,rooms+1):#to handle the small positive 

        for x in adj[i]:
             for j in range(len(data['edges'])):
                if (data['edges'][j]['source'] == x and data['edges'][j]['target'] == i) or (data['edges'][j]['source'] == i and data['edges'][j]['target'] == x) :
                    if(data ['edges'][j]['color'] == 'red') :
                        small_positive = 0.1
                    elif(data ['edges'][j]['color'] == 'black'):
                        small_positive = 2
             #print("Change to be noted",small_positive)
             type_val = adj_type[(i, x)]
             if type_val==1 or type_val==2:
                 a=placementy[2*x]+small_positive
                 b=placementy[2*x-1]-small_positive
                 if roty1[2*i-2]<a:
                    roty1[2*i-2]=a
                 if roty2[2*i-1]>b:
                    #print("small positive",small_positive)
                    #print("change in rot",b,i,x)
                    roty2[2*i-1]=b 
             if type_val==3 or type_val==4:
                 a=placementx[2*x-1]+small_positive
                 b=placementx[2*x]-small_positive
                 if rotx1[2*i-1]<a:
                    rotx1[2*i-1]=a
                 if rotx2[2*i-2]>b:
                    rotx2[2*i-2]=b 
    #print("debug",roty2[5])
    for i in range(1,rooms+1):#to make sure that same walls have same range of tolerance
        for x in adj[i]:
            type_val=adj_type[(i,x)]
            if type_val==1:
                a=max(rotx1[2*i-2],rotx1[2*x-1])
                b=min(rotx2[2*i-2],rotx2[2*x-1])
                rotx1[2*i-2]=a
                rotx1[2*x-1]=a
                rotx2[2*i-2]=b
                rotx2[2*x-1]=b     
            elif type_val==2:
                a=max(rotx1[2*i-1],rotx1[2*x-2])
                b=min(rotx2[2*i-1],rotx2[2*x-2])
                rotx1[2*i-1]=a
                rotx1[2*x-2]=a
                rotx2[2*i-1]=b
                rotx2[2*x-2]=b                           
            elif type_val==3:
                a=max(roty1[2*i-2],roty1[2*x-1])
                b=min(roty2[2*i-2],roty2[2*x-1])
                roty1[2*i-2]=a
                roty1[2*x-1]=a
                roty2[2*i-2]=b
                roty2[2*x-1]=b 
            elif type_val==4:
                a=max(roty1[2*i-1],roty1[2*x-2])
                b=min(roty2[2*i-1],roty2[2*x-2])
                roty1[2*i-1]=a
                roty1[2*x-2]=a
                roty2[2*i-1]=b
                roty2[2*x-2]=b      
    #print("debug",roty2[5])    
                


                

# function for printing range of tolerance
def print_rot():
    print("Range of tolerance in x direction")
    for i in range (2*rooms):
        print(i+1,rotx1[i],rotx2[i])
    print("Range of tolerance in y direction")  
    for i in range (2*rooms):
        print(i+1,roty1[i],roty2[i])

# debugging function
def print_input():
    print(adj_type)
    print(lb_len)
    print(ub_len)
    print(lb_width)
    print(ub_width)

#updating placement of west and south boundary rooms based on range of tolerance to minimize area
def edit_placements():
    for i in range(len(data['boundary_rooms']['west'])):
        j = data['boundary_rooms']['west'][i]
        if rotx2[2*j-2] > placementx[2*j-1]:
            placementx[2*j-1] = rotx2[2*j-2]
            # print('changing x position of wall', j*2-1, 'to ', placementx[2*j-1])
    
    for i in range(len(data['boundary_rooms']['south'])):
        j = data['boundary_rooms']['south'][i]
        if roty2[2*j-1] > placementy[2*j]:
            placementy[2*j] = roty2[2*j-1]
            # print('changing y position of wall ', j*2, 'to ', placementy[2*j])
    
    
# the final file to be given to gplan to show in UI
def return_output():
    global placementx,placementy,data
    out_data={'nodes':[]}
    for i in range(rooms):
        dic={}
        dic.update({'id':data['nodes'][i]['id']})
        if 'label' in data['nodes'][i]:
            dic.update({'label':data['nodes'][i]['label']})
        dic.update({'room_x':float(round(placementx[2*i+1],4))})
        dic.update({'room_y':float(round(placementy[2*i+2],4))})
        dic.update({'width':float(round(placementx[2*i+2],4)-round(placementx[2*i+1],4))})
        dic.update({'height':float(round(placementy[2*i+1],4)-round(placementy[2*i+2],4))})
        out_data['nodes'].append(dic)
    # print(out_data)

    return out_data

 

def reinitialize():
    global rooms,num_sx,num_tx,num_sy,num_ty,sx_adj,sy_adj,adjacent_pairs,adj,adj_type,edgesX,edgesY,edges_setx,edges_sety,lb_len,ub_len,lb_width,ub_width,placementx,placementy,tx_adj,ty_adj,plot_width,plot_height,rotx1,rotx2,roty1,roty2
    rooms = 0
    num_sx, num_tx, num_sy, num_ty = 0, 0, 0, 0
    sx_adj = []
    sy_adj = []
    tx_adj=[]
    ty_adj=[]

    adjacent_pairs = 0
    adj = defaultdict(list)  # contains the adjacency of all the rooms
    adj_type = {}

    edgesX = []
    edgesY = []
    edges_setx = []
    edges_sety = []

    lb_len = []
    ub_len = []
    lb_width = []
    ub_width = []
    plot_width = 0
    plot_height = 0

    placementx = []
    placementy = []

    rotx1=[]
    rotx2=[]
    roty1=[]
    roty2=[]

    irreg_nodes_map.clear()
    door_connectivity_edges.clear()

    global adjacency_overlap_floor
    adjacency_overlap_floor = DOOR_OVERLAP_FLOOR


# main wrapper
def main(input, plot_width, plot_height, overlap_floor=None):
    """`overlap_floor` overrides the briefed-adjacency shared-wall minimum for
    THIS solve (feet). None = DOOR_OVERLAP_FLOOR. solve_min_dim passes the
    legacy 2.0 as a relaxation rung when the door-width floor makes a topology
    infeasible."""
    global data, irreg_nodes_map
    reinitialize()
    if overlap_floor is not None:
        globals()['adjacency_overlap_floor'] = float(overlap_floor)
# <<<<<<< main
    data = input

    # Store the all dummy nodes as the value of the irregular rooms they are adjacent to
    if 'mergednodes' in data and 'irreg_nodes1' in data and 'irreg_nodes2' in data:
        for i in range(0, len(data['mergednodes'])):
            irreg_nodes_map[(data['irreg_nodes1'][i], data['irreg_nodes2'][i])] = data['mergednodes'][i]
    
    # If dummy nodes exist, remove the adjacency between irregular rooms as they are now separated by dummy nodes
    if 'dummy_node_adj' in data:
        for a in data['edges']:

            # Add the edges with door connectivity to the door_connectivity_edges set
            if a['color'] == 'black':
                continue

            # If there is door connectivity between irregular nodes separated by a dummy node, add a door connectivity between the dummy node and irregular node instead
            elif (a['source'], a['target']) in irreg_nodes_map:
                door_connectivity_edges.add((irreg_nodes_map[(a['source'], a['target'])], a['target']))
            elif (a['target'], a['source']) in irreg_nodes_map:
                door_connectivity_edges.add((irreg_nodes_map[(a['target'], a['source'])], a['source']))
            else:
                door_connectivity_edges.add((a['source'], a['target']))
        data['edges'].clear()

        # Update modified edge data
        for a in data['dummy_node_adj']:
            color = 'black'
            if ((a[0], a[1]) in door_connectivity_edges or (a[1], a[0]) in door_connectivity_edges):
                color = 'red'
            data['edges'].append({'source':a[0] + 1, 'target':a[1] + 1, 'color':color})
    else:
        for a in data['edges']:
            a['source']=a['source']+1
            a['target']=a['target']+1
# =======
#     f = open(file_path)
#     data = json.load(f)
#     # print(data)
#     # print(data['edges'][0])
#     for a in data['edges']:
#         a['source']=a['source']+1
#         a['target']=a['target']+1
# >>>>>>> Door_connectivity_cleanup
    for i in range(len(data['boundary_rooms']['north'])):
        data['boundary_rooms']['north'][i]= data['boundary_rooms']['north'][i]+1
    for i in range(len(data['boundary_rooms']['south'])):
        data['boundary_rooms']['south'][i]= data['boundary_rooms']['south'][i]+1
    for i in range(len(data['boundary_rooms']['east'])):
        data['boundary_rooms']['east'][i]= data['boundary_rooms']['east'][i]+1
    for i in range(len(data['boundary_rooms']['west'])):
        data['boundary_rooms']['west'][i]= data['boundary_rooms']['west'][i]+1
    globals()['plot_width'] = plot_width
    globals()['plot_height'] = plot_height
        
    input_data()  # Take all the necessary inputs
    # print_input()

    construct_constraintgraphX()  # Using the inputs, construct X constraint graph
    construct_constraintgraphY()  # Construct Y constraint graph
    # print_edges()  # Print edges for X and Y constraints
    if not compute_placement():  # Compute placements using longest path algorithm and return false if no legal placement found
        # print_placements()
        return [False, None]
    # print_placements()  # Print computed placements
    compute_rot()
    # print_rot()
    edit_placements()
    out_data = return_output()
    return [True, out_data]

# Main execution
# main(file_path)

if __name__ == "__main__":
    main("input_to_min_dim.json")
